### ISSUE TITLE
PS2 model is a bit strange…

### ISSUE THREAD

**Issue by StenApp** [Five-Damned-Dollarz/io_scene_lithtech#3]
Well it seems to me that i can import hero_thief.ltb and export it with base and hip animation as lta, i loose sockets.

whereas convert ltb to lta model keeps sockets and mangels up the model, looks exploded.
[hero_thief_blender export as lta.zip](https://github.com/Five-Damned-Dollarz/io_scene_lithtech/files/15225638/hero_thief_blender.export.as.lta.zip)
[hero_thief_blender directly converted ltb to lta.zip](https://github.com/Five-Damned-Dollarz/io_scene_lithtech/files/15225640/hero_thief_blender.directly.converted.ltb.to.lta.zip)
[hero_thief.ltb.txt](https://github.com/Five-Damned-Dollarz/io_scene_lithtech/files/15225661/hero_thief.ltb.txt)

**Comment by StenApp** [comment]
<img width="566" alt="2024-05-10 13_55_58-ModelEdit" src="https://github.com/Five-Damned-Dollarz/io_scene_lithtech/assets/32524257/e5ccb6ad-ed78-4b7d-8099-7b1c703c729e">

**Comment by StenApp** [comment]
<img width="567" alt="2024-05-10 13_57_49-ModelEdit2" src="https://github.com/Five-Damned-Dollarz/io_scene_lithtech/assets/32524257/801c24a0-3236-4a3b-a6c9-cf26823ea8e5">

**Comment by Five-Damned-Dollarz** [comment]
> Well it seems to me that i can import hero_thief.ltb and export it with base and hip animation as lta, i loose sockets.

Make sure you tick import sockets. I checked myself, they import and export fine.
> whereas convert ltb to lta model keeps sockets and mangels up the model, looks exploded.

Misremembered what type of LTB this was, in actuality it's because of some unnecessary ModelStubber code, I'll remove that.
~Haven't looked at this, but my guess is that it's not version checking and making the same mistake as the template, as mentioned in #5, if so it should be a pretty easy fix.~
